name = "SysBioRegistryTemplate"
uuid = "42af7cd6-1508-452d-b1e6-ea2b692d8789"
authors = ["Chris Damour"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
